---
- hosts: all
  vars:
    minio_activate: false
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - command: /usr/local/bin/minio --version
      register: minio_test_output
    - name: minio --version
      debug:
        msg: '{{ minio_test_output.stdout }}'
    - command: /usr/local/bin/mc --version
      register: mc_test_output
    - name: mc --versison
      debug:
        msg: '{{ mc_test_output.stdout }}'
