---
- name: Testing install for minio and mc
  hosts: all
  vars:
    minio_activate: false
  tasks:
    - name: Install andrewrothstein.minio
      ansible.builtin.include_role:
        name: '{{ playbook_dir }}'
    - name: Executing 'minio --version'
      ansible.builtin.command: /usr/local/bin/minio --version
      changed_when: false
      register: minio_test_output
    - name: Output of 'minio --version'
      ansible.builtin.debug:
        msg: '{{ minio_test_output.stdout }}'
    - name: Executing 'mc --version'
      ansible.builtin.command: /usr/local/bin/mc --version
      changed_when: false
      register: mc_test_output
    - name: Output of 'mc --version'
      ansible.builtin.debug:
        msg: '{{ mc_test_output.stdout }}'
