---
- hosts: all
  vars:
    minio_activate: false
    minio_config:
      enable: true
      server_access_key: minioServerAccessKey
      server_secret_key: minioServerSecretKey
      user: minio-test-user
      group: minio-test-group
      working_dir: /usr/local/
      config_file: /etc/default/minio
      volumes:
        - /data/disk1
        - /data/disk2
        - /data/disk3
  roles:
    - role: '{{ playbook_dir }}'
