---
- name: install brew package
  become: '{{ minio_privilege_escalate }}'
  become_user: '{{ minio_privilege_escalation_user }}'
  loop: '{{ minio_components }}'
  homebrew:
    name: minio/stable/{{ item }}
    state: present
