---
- name: Install homebrew packages
  become: '{{ minio_privilege_escalate }}'
  become_user: '{{ minio_privilege_escalation_user }}'
  loop: '{{ minio_components }}'
  community.general.homebrew:
    name: minio/stable/{{ item }}
    state: present
