---
- name: download and install
  loop: '{{ minio_apps | selectattr("name", "in", minio_components) | list }}'
  loop_control:
    loop_var: minio_app
  include_tasks: install-{{ minio_installer }}.yml
- when: minio_config is defined and minio_config.enable
  include_tasks: configure.yml
