---
- name: templatizing minio.service
  become: yes
  become_user: root
  template:
    src: minio.service.j2
    dest: /etc/systemd/system/minio.service
    mode: 0644
  notify: minio_daemon_reload
