---
- name: Templatizing minio.service
  become: '{{ minio_privilege_escalate }}'
  become_user: '{{ minio_privilege_escalation_user }}'
  ansible.builtin.template:
    src: minio.service.j2
    dest: /etc/systemd/system/minio.service
    mode: '644'
  notify: Minio Daemon Reload
