---
- name: templatizing minio.service
  become: '{{ minio_privilege_escalate }}'
  become_user: '{{ minio_privilege_escalation_user }}'
  template:
    src: minio.service.j2
    dest: /etc/systemd/system/minio.service
    mode: 0644
  notify: minio_daemon_reload
