---
# handlers file for minio
- name: Minio Daemon Reload
  become: true
  become_user: root
  when: minio_activate
  ansible.builtin.systemd:
    daemon_reload: true
- name: Minio Daemon Restart
  become: true
  become_user: root
  when: minio_activate
  ansible.builtin.service:
    name: minio
    state: restarted
