---
# handlers file for minio
- name: minio_daemon_reload
  become: true
  become_user: root
  when: minio_activate
  ansible.builtin.systemd:
    daemon_reload: true
- name: minio_restart
  become: true
  become_user: root
  when: minio_activate
  ansible.builtin.service:
    name: minio
    state: restarted
