---
# handlers file for minio
- name: minio_daemon_reload
  become: yes
  become_user: root
  when: minio_activate
  systemd:
    daemon_reload: yes
- name: minio_restart
  become: yes
  become_user: root
  when: minio_activate
  service:
    name: minio
    state: restarted
